on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Buildt index.html file
              run: python build.py

            - name: Upload built files
              uses: actions/upload-pages-artifact@v3
              with:
                path: out/

    deploy:
        runs-on: ubuntu-latest
        environment: 
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        needs: build
        permissions:
            pages: write
            id-token: write
        steps:
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
    snake:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
          - name: generate github-contribution-grid-snake.svg
            uses: Platane/snk@v3.2.0
            with:
                # github user name to read the contribution graph from (**required**)
                # using action context var `github.repository_owner` or specified user
                github_user_name: ${{ OllieBlomfield }}
                
                # list of files to generate.
                # one file per line. Each output can be customized with options as query string.
                #
                #  supported options:
                #  - palette:     A preset of color, one of [github, github-dark, github-light]
                #  - color_snake: Color of the snake
                #  - color_dots:  Coma separated list of dots color.
                #                 The first one is 0 contribution, then it goes from the low contribution to the highest.
                #                 Exactly 5 colors are expected.
                outputs: |
                    dist/github-snake.svg
                    dist/github-snake-dark.svg?palette=github-dark
                    dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
